name: swapnabaj
description: "Swapnabaj - Bondhu Mohol"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6 # State Management!
  shared_preferences: ^2.2.2 # Local Storage!
  cloud_firestore: ^5.4.2 # server Storage!
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0

  # UI Helpers!
  fl_chart: ^0.69.0
  shimmer: ^3.0.0

  # Localization!
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/saeid.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
